PassionProject/Models/WorkOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class WorkOrder
    {
        [Key]
        public int WorkOrderID { get; set; }

        [Required, StringLength(255), Display(Name = "Work Order Name")]
        public string WorkOrderName { get; set; }

        [Required, StringLength(255), Display(Name = "Customer Name")]
        public string WorkOrderCustomerName { get; set; }

        [Required, Display(Name = "Price")]
        [DataType(DataType.Currency)]
        public float WorkOrderPrice { get; set; }


        //reffered https://www.c-sharpcorner.com/article/displaying-calender-control-in-Asp-Net-mvc-without-jquery-an/ for calender control
        [Required,Display(Name ="Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? StartDate { get; set; }

        [Required, Display(Name = "Expected Finish Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FinishDate { get; set; }

        //One workorder can have many laptops associated with it.
        public virtual ICollection<Laptops> Laptops { get; set; }
    }
}

PassionProject/ViewModels/WorkOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PassionProject.Models;

namespace PassionProject.ViewModels
{
    public class WorkOrderViewModel
    {
        //Empty constructor
        public WorkOrderViewModel()
        {

        }

        //Raw page information (in Models/WorkOrder.cs)
        public virtual WorkOrder workOrder { get; set; }

        //need information about the different laptops this workorder COULD be
        //assigned to
        public IEnumerable<Laptops>  laptops { get; set; }
    }
}

PassionProject/Controllers/LaptopController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using PassionProject.ViewModels;

namespace PassionProject.Controllers
{
    public class LaptopController : Controller
    {
        private LaptopRepairDbContext db = new LaptopRepairDbContext();
        // GET: Laptop
        public ActionResult Index()
        {            
            return View(db.Laptops.ToList());
        }

        public ActionResult Create()
        {
            LaptopRepairViewModel laptopRepairViewModel = new LaptopRepairViewModel();
            laptopRepairViewModel.workOrders = db.WorkOrders.ToList();
            return View(laptopRepairViewModel);

        }

        //Restricts this method to only handle POST
        //eg. POST to /Pages/Create/
        [HttpPost, ActionName("Create")]
        public ActionResult Create(string LaptopManufacturer_New, string LaptopModel_New, string LaptopProblem_New, int? LaptopWorkOrder_New)
        {
            string query = "insert into Laptops (LaptopManufacturer, LaptopModel, LaptopProblem,Workorder_WorkOrderID) " +
                "values (@LaptopManufacturer,@LaptopModel,@LaptopProblem,@Workorder_WorkOrderID)";

            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@LaptopManufacturer", LaptopManufacturer_New);
            myparams[1] = new SqlParameter("@LaptopModel", LaptopModel_New);
            myparams[2] = new SqlParameter("@LaptopProblem", LaptopProblem_New);
            myparams[3] = new SqlParameter("@Workorder_WorkOrderID", LaptopWorkOrder_New);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? id)
        {
            LaptopRepairViewModel laptopRepairViewModel = new LaptopRepairViewModel();
            laptopRepairViewModel.Laptops = db.Laptops.Find(id);
            laptopRepairViewModel.workOrders = db.WorkOrders.ToList();
            if (laptopRepairViewModel.Laptops != null)
                return View(laptopRepairViewModel);
            else
                return HttpNotFound();
        }

        //This one actually does the editing commmand
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(int? id, string LaptopManufacturer_Edit, string LaptopModel_Edit, string LaptopProblem_Edit, int LaptopWorkOrder_Edit)
        {
            if ((id == null) || (db.Laptops.Find(id) == null))
            {
                return HttpNotFound();

            }
            /*enter data for page*/
            string query = "update Laptops set LaptopManufacturer=@LaptopManufacturer, " +
                "LaptopModel=@LaptopModel, " +
                "LaptopProblem=@LaptopProblem, " +
                "Workorder_WorkorderID=@Workorder where LaptopID = @LaptopID";

            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@LaptopManufacturer", LaptopManufacturer_Edit);
            myparams[1] = new SqlParameter("@LaptopModel", LaptopModel_Edit);
            myparams[2] = new SqlParameter("@LaptopProblem", LaptopProblem_Edit);
            myparams[3] = new SqlParameter("@Workorder", LaptopWorkOrder_Edit);
            myparams[4] = new SqlParameter("@LaptopID", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Details/" + id);
        }

        public ActionResult Details(int id)
        {
            string query = "select * from Laptops where LaptopID =@id";
            return View(db.Laptops.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Laptops laptops = db.Laptops.Find(id);

            if (laptops == null)
            {
                return HttpNotFound();
            }
            return View(laptops);
        }

        //GET of localhost/Laptop/delete/2
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string query = "delete from Laptops where LaptopID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            return RedirectToAction("Index");
        }
    }
}

PassionProject/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using PassionProject.ViewModels;

namespace PassionProject.Controllers
{
    public class WorkOrderController : Controller
    {
        //Refferenced code from the sample project done by Christine

        private LaptopRepairDbContext db = new LaptopRepairDbContext();
        // GET: WorkOrder
        public ActionResult Index()
        {
            return View(db.WorkOrders.ToList());
        }

        public ActionResult Create()
        {            
            return View();
        }

        //Restricts this method to only handle POST
        //eg. POST to /Pages/Create/
        [HttpPost]
        public ActionResult Create(string WorkOrderName_New, string WorkOrderCustomerName_New, float? WorkOrderPrice_New,DateTime? WorkOrderStartDate_New,DateTime? WorkOrderFinishDate_New)
        {
            string query = "insert into WorkOrders (WorkOrderName, WorkOrderCustomerName, WorkOrderPrice,StartDate,FinishDate) " +
                "values (@WorkOrderName,@WorkOrderCustomerName,@WorkOrderPrice,@StartDate,@FinishDate)";

            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@WorkOrderName", WorkOrderName_New);
            myparams[1] = new SqlParameter("@WorkOrderCustomerName", WorkOrderCustomerName_New);
            myparams[2] = new SqlParameter("@WorkOrderPrice", WorkOrderPrice_New);
            myparams[3] = new SqlParameter("@StartDate", WorkOrderStartDate_New);
            myparams[4] = new SqlParameter("@FinishDate", WorkOrderFinishDate_New);

            db.Database.ExecuteSqlCommand(query, myparams);
            
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            string query = "select * from WorkOrders where WorkOrderID =@id";
            return View(db.WorkOrders.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Edit(int? id)
        {
            WorkOrderViewModel workOrderViewModel = new WorkOrderViewModel();
            workOrderViewModel.workOrder = db.WorkOrders.Find(id);
            workOrderViewModel.laptops = db.Laptops.ToList();
            if (workOrderViewModel.workOrder != null)
                return View(workOrderViewModel);
            else
                return HttpNotFound();
        }

        //This one actually does the editing commmand
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(int? id, string WorkOrderName_Edit, string WorkOrderCustomerName_Edit, int? WorkOrderPrice_Edit, DateTime? WorkOrderStartDate_Edit, DateTime? WorkOrderFinishDate_Edit)
        {
            if ((id == null) || (db.WorkOrders.Find(id) == null))
            {
                return HttpNotFound();

            }
            /*enter data for page*/
            string query = "update WorkOrders set WorkOrderName=@WorkOrderName, " +
                "WorkOrderCustomerName=@WorkOrderCustomerName, " +
                "WorkOrderPrice=@WorkOrderPrice, " +
                "StartDate=@StartDate, " +
                "FinishDate=@FinishDate where WorkOrderID = @WorkOrderID";

            SqlParameter[] myparams = new SqlParameter[6];
            myparams[0] = new SqlParameter("@WorkOrderName", WorkOrderName_Edit);
            myparams[1] = new SqlParameter("@WorkOrderCustomerName", WorkOrderCustomerName_Edit);
            myparams[2] = new SqlParameter("@WorkOrderPrice", WorkOrderPrice_Edit);
            myparams[3] = new SqlParameter("@StartDate", WorkOrderStartDate_Edit);
            myparams[4] = new SqlParameter("@FinishDate", WorkOrderFinishDate_Edit);
            myparams[5] = new SqlParameter("@WorkOrderID", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Details/" + id);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder= db.WorkOrders.Find(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        //GET of localhost/WorkOrder/delete/2
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string query = "delete from Laptops where Workorder_WorkOrderID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            query = "delete from Workorders where WorkOrderID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            return RedirectToAction("Index");
        }

    }
}

PassionProject/Views/WorkOrder/Create.cshtml
@model PassionProject.Models.WorkOrder

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Work Order</h2>

<form method="POST" action="/WorkOrder/Create">
    <div class="inprow">
        <label class="inplabel">Work Order Name</label>
        <input id="WorkOrderName_New" name="WorkOrderName_New" />
    </div>
    <div class="inprow">
        <label class="inplabel">Customer Name</label>
        <input id="WorkOrderCustomerName_New" name="WorkOrderCustomerName_New" />
    </div>
    <div class="inprow">
        <label class="inplabel">Price</label>
        $<input id="WorkOrderPrice_New" name="WorkOrderPrice_New"  />
    </div>
    <div class="inprow">
        <label class="inplabel">Work Order Start Date</label>
        <input type="date" class="datecontrol" id="WorkOrderStartDate_New" name="WorkOrderStartDate_New" />
    </div>
    <div class="inprow">
        <label class="inplabel">Expected Work Order Finish Date</label>
        <input type="date" class="datecontrol" id="WorkOrderFinishDate_New" name="WorkOrderFinishDate_New" />
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/WorkOrder/Delete.cshtml
@model PassionProject.Models.WorkOrder

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkOrderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkOrderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkOrderCustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkOrderCustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkOrderPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkOrderPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinishDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PassionProject/Views/WorkOrder/Details.cshtml
@model PassionProject.Models.WorkOrder

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="inprow">
    <label class="inplabel">Work Order Name: </label>@Model.WorkOrderName
</div>
<div class="inprow">
    <label class="inplabel">Customer Name: </label>@Model.WorkOrderCustomerName
</div>
<div class="inprow">
    <label class="inplabel">Price: $</label>@Model.WorkOrderPrice
</div>
@* reffered https://stackoverflow.com/questions/6001654/how-to-render-a-datetime-in-a-specific-format-in-asp-net-mvc-3
    for date format in model answered by Nick Larsen*@

<div class="inprow">
    <label class="inplabel">Start Date: </label>@Html.DisplayFor(m => m.StartDate, "ShortDateTime")
</div>
<div class="inprow">
    <label class="inplabel">Finish Date: </label>@Html.DisplayFor(m => m.FinishDate, "ShortDateTime")
</div>
<h4>Laptops under this work order</h4>
<div class="inprow">
    @*@foreach (var laptop in Model.Laptops)
        {
            <div class="recitem">
                @Html.ActionLink(laptop.LaptopModel, "Details/" + laptop.LaptopID, "Laptop")
            </div>
        }*@

    <table class="table">
        <tr>
            <th>
                Laptop Model
            </th>
            <th>
                Laptop Problem
            </th>
        </tr>

        @foreach (var laptop in Model.Laptops)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => laptop.LaptopModel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => laptop.LaptopProblem)
                </td>
            </tr>
        }

    </table>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WorkOrderID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PassionProject/Views/WorkOrder/Edit.cshtml
@model PassionProject.ViewModels.WorkOrderViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<form method="POST" action="/WorkOrder/Edit/@Model.workOrder.WorkOrderID">
    <div class="inprow">
        <label class="inplabel">Work Order Name</label>
        <input id="WorkOrderName_Edit" name="WorkOrderName_Edit" value="@Model.workOrder.WorkOrderName" />
    </div>
    <div class="inprow">
        <label class="inplabel">Customer Name</label>
        <input id="WorkOrderCustomerName_Edit" name="WorkOrderCustomerName_Edit" value="@Model.workOrder.WorkOrderCustomerName" />
    </div>
    <div class="inprow">
        <label class="inplabel">Price</label>
        $<input id="WorkOrderPrice_Edit" name="WorkOrderPrice_Edit" value="@Model.workOrder.WorkOrderPrice" />
    </div>
    <div class="inprow">
        <label class="inplabel">Work Order Start Date</label>
        <input type="date" class="datecontrol" id="WorkOrderStartDate_Edit" name="WorkOrderStartDate_Edit" value="@Model.workOrder.StartDate" />
        @*<input type="date" class="datecontrol" id="WorkOrderStartDate_Edit" name="WorkOrderStartDate_Edit" value="@Html.DisplayFor(m => m.workOrder.StartDate, "LongDateTime")" />*@
        @*@Html.TextBoxFor(Model => Model.workOrder.StartDate, new { type = "date" })*@
    </div>
    <div class="inprow">
        <label class="inplabel">Expected Work Order Finish Date</label>
        <input type="date" class="datecontrol" id="WorkOrderFinishDate_Edit" name="WorkOrderFinishDate_Edit"  value="@Model.workOrder.FinishDate"/>
        
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/WorkOrder/Index.cshtml
@model IEnumerable<PassionProject.Models.WorkOrder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.WorkOrderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkOrderCustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkOrderPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinishDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.WorkOrderName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkOrderCustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkOrderPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinishDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.WorkOrderID }) |
            @Html.ActionLink("Details", "Details", new { id = item.WorkOrderID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.WorkOrderID })
        </td>
    </tr>
}

</table>