PassionProject/Models/Laptops.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace PassionProject.Models
{
    public class Laptops
    {
        //Referred from sample project of Christine

        [Key, ScaffoldColumn(false)]
        public int LaptopID { get; set; }

        //required string length up to 255 characters,
        //labelled as "Manufacturer"
        [Required, StringLength(255), Display(Name = "Manufacturer")]
        public string LaptopManufacturer { get; set; }

        //Laptop Model
        [Required, StringLength(255), Display(Name = "Model")]
        public string LaptopModel { get; set; }

        //Laptop Problem
        [StringLength(int.MaxValue), Display(Name = "Problem")]
        public string LaptopProblem { get; set; }

        //One workorder to many laptops
        public virtual WorkOrder Workorder { get; set; }
    }
}

PassionProject/Controllers/LaptopController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using PassionProject.ViewModels;

namespace PassionProject.Controllers
{
    public class LaptopController : Controller
    {
        private LaptopRepairDbContext db = new LaptopRepairDbContext();
        // GET: Laptop
        public ActionResult Index()
        {            
            return View(db.Laptops.ToList());
        }

        public ActionResult Create()
        {
            LaptopRepairViewModel laptopRepairViewModel = new LaptopRepairViewModel();
            laptopRepairViewModel.workOrders = db.WorkOrders.ToList();
            return View(laptopRepairViewModel);

        }

        //Restricts this method to only handle POST
        //eg. POST to /Pages/Create/
        [HttpPost, ActionName("Create")]
        public ActionResult Create(string LaptopManufacturer_New, string LaptopModel_New, string LaptopProblem_New, int? LaptopWorkOrder_New)
        {
            string query = "insert into Laptops (LaptopManufacturer, LaptopModel, LaptopProblem,Workorder_WorkOrderID) " +
                "values (@LaptopManufacturer,@LaptopModel,@LaptopProblem,@Workorder_WorkOrderID)";

            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@LaptopManufacturer", LaptopManufacturer_New);
            myparams[1] = new SqlParameter("@LaptopModel", LaptopModel_New);
            myparams[2] = new SqlParameter("@LaptopProblem", LaptopProblem_New);
            myparams[3] = new SqlParameter("@Workorder_WorkOrderID", LaptopWorkOrder_New);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Index");
        }


        public ActionResult Edit(int? id)
        {
            LaptopRepairViewModel laptopRepairViewModel = new LaptopRepairViewModel();
            laptopRepairViewModel.Laptops = db.Laptops.Find(id);
            laptopRepairViewModel.workOrders = db.WorkOrders.ToList();
            if (laptopRepairViewModel.Laptops != null)
                return View(laptopRepairViewModel);
            else
                return HttpNotFound();
        }

        //This one actually does the editing commmand
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(int? id, string LaptopManufacturer_Edit, string LaptopModel_Edit, string LaptopProblem_Edit, int LaptopWorkOrder_Edit)
        {
            if ((id == null) || (db.Laptops.Find(id) == null))
            {
                return HttpNotFound();

            }
            /*enter data for page*/
            string query = "update Laptops set LaptopManufacturer=@LaptopManufacturer, " +
                "LaptopModel=@LaptopModel, " +
                "LaptopProblem=@LaptopProblem, " +
                "Workorder_WorkorderID=@Workorder where LaptopID = @LaptopID";

            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@LaptopManufacturer", LaptopManufacturer_Edit);
            myparams[1] = new SqlParameter("@LaptopModel", LaptopModel_Edit);
            myparams[2] = new SqlParameter("@LaptopProblem", LaptopProblem_Edit);
            myparams[3] = new SqlParameter("@Workorder", LaptopWorkOrder_Edit);
            myparams[4] = new SqlParameter("@LaptopID", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Details/" + id);
        }

        public ActionResult Details(int id)
        {
            string query = "select * from Laptops where LaptopID =@id";
            return View(db.Laptops.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Laptops laptops = db.Laptops.Find(id);

            if (laptops == null)
            {
                return HttpNotFound();
            }
            return View(laptops);
        }

        //GET of localhost/Laptop/delete/2
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string query = "delete from Laptops where LaptopID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            return RedirectToAction("Index");
        }
    }
}

PassionProject/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using PassionProject.ViewModels;

namespace PassionProject.Controllers
{
    public class WorkOrderController : Controller
    {
        //Refferenced code from the sample project done by Christine

        private LaptopRepairDbContext db = new LaptopRepairDbContext();
        // GET: WorkOrder
        public ActionResult Index()
        {
            return View(db.WorkOrders.ToList());
        }

        public ActionResult Create()
        {            
            return View();
        }

        //Restricts this method to only handle POST
        //eg. POST to /Pages/Create/
        [HttpPost]
        public ActionResult Create(string WorkOrderName_New, string WorkOrderCustomerName_New, float? WorkOrderPrice_New,DateTime? WorkOrderStartDate_New,DateTime? WorkOrderFinishDate_New)
        {
            string query = "insert into WorkOrders (WorkOrderName, WorkOrderCustomerName, WorkOrderPrice,StartDate,FinishDate) " +
                "values (@WorkOrderName,@WorkOrderCustomerName,@WorkOrderPrice,@StartDate,@FinishDate)";

            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@WorkOrderName", WorkOrderName_New);
            myparams[1] = new SqlParameter("@WorkOrderCustomerName", WorkOrderCustomerName_New);
            myparams[2] = new SqlParameter("@WorkOrderPrice", WorkOrderPrice_New);
            myparams[3] = new SqlParameter("@StartDate", WorkOrderStartDate_New);
            myparams[4] = new SqlParameter("@FinishDate", WorkOrderFinishDate_New);

            db.Database.ExecuteSqlCommand(query, myparams);
            
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            string query = "select * from WorkOrders where WorkOrderID =@id";
            return View(db.WorkOrders.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        public ActionResult Edit(int? id)
        {
            WorkOrderViewModel workOrderViewModel = new WorkOrderViewModel();
            workOrderViewModel.workOrder = db.WorkOrders.Find(id);
            workOrderViewModel.laptops = db.Laptops.ToList();
            if (workOrderViewModel.workOrder != null)
                return View(workOrderViewModel);
            else
                return HttpNotFound();
        }

        //This one actually does the editing commmand
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(int? id, string WorkOrderName_Edit, string WorkOrderCustomerName_Edit, int? WorkOrderPrice_Edit, DateTime? WorkOrderStartDate_Edit, DateTime? WorkOrderFinishDate_Edit)
        {
            if ((id == null) || (db.WorkOrders.Find(id) == null))
            {
                return HttpNotFound();

            }
            /*enter data for page*/
            string query = "update WorkOrders set WorkOrderName=@WorkOrderName, " +
                "WorkOrderCustomerName=@WorkOrderCustomerName, " +
                "WorkOrderPrice=@WorkOrderPrice, " +
                "StartDate=@StartDate, " +
                "FinishDate=@FinishDate where WorkOrderID = @WorkOrderID";

            SqlParameter[] myparams = new SqlParameter[6];
            myparams[0] = new SqlParameter("@WorkOrderName", WorkOrderName_Edit);
            myparams[1] = new SqlParameter("@WorkOrderCustomerName", WorkOrderCustomerName_Edit);
            myparams[2] = new SqlParameter("@WorkOrderPrice", WorkOrderPrice_Edit);
            myparams[3] = new SqlParameter("@StartDate", WorkOrderStartDate_Edit);
            myparams[4] = new SqlParameter("@FinishDate", WorkOrderFinishDate_Edit);
            myparams[5] = new SqlParameter("@WorkOrderID", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Details/" + id);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder= db.WorkOrders.Find(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        //GET of localhost/WorkOrder/delete/2
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            string query = "delete from Laptops where Workorder_WorkOrderID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            query = "delete from Workorders where WorkOrderID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            return RedirectToAction("Index");
        }

    }
}

PassionProject/Views/Laptop/Create.cshtml
@model PassionProject.ViewModels.LaptopRepairViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>



<form method="POST" action="/Laptop/Create">
    <div class="inprow">
        <label class="inplabel">Manufacturer</label>
        <input id="LaptopManufacturer_New" name="LaptopManufacturer_New" />
    </div>
    <div class="inprow">
        <label class="inplabel">Model</label>
        <input id="LaptopModel_New" name="LaptopModel_New" />
    </div>
    <div class="inprow">
        <label class="inplabel">Problem</label>
        <input id="LaptopProblem_New" name="LaptopProblem_New" />
    </div>
    <div class="inprow">
        <label class="inplabel">Work Order</label>
        <select id="LaptopWorkOrder_New" class="LaptopWorkorderDropdown" name="LaptopWorkOrder_New">
            @foreach (var workOrder in Model.workOrders)
            {
                <option value="@workOrder.WorkOrderID">@workOrder.WorkOrderName</option>
            }

        </select>
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/Laptop/Delete.cshtml
@model PassionProject.Models.Laptops

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Laptops</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LaptopManufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaptopManufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaptopModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaptopModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaptopProblem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaptopProblem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Workorder.WorkOrderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Workorder.WorkOrderName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PassionProject/Views/Laptop/Details.cshtml
@model PassionProject.Models.Laptops

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="inprow">
    <label class="inplabel">Manufacturer: </label>@Model.LaptopManufacturer
</div>
<div class="inprow">
    <label class="inplabel">Model: </label>@Model.LaptopModel
</div>
<div class="inprow">
    <label class="inplabel">Problem: </label>@Model.LaptopProblem
</div>
<div class="inprow">
    <label class="inplabel">Work Order: </label>@Model.Workorder.WorkOrderName
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LaptopID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PassionProject/Views/Laptop/Edit.cshtml
+-@model PassionProject.ViewModels.LaptopRepairViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<form method="POST" action="/Laptop/Edit/@Model.Laptops.LaptopID">
    <div class="inprow">
        <label class="inplabel">Manufacturer</label>
        <input id="LaptopManufacturer_Edit" name="LaptopManufacturer_Edit" value="@Model.Laptops.LaptopManufacturer" />
    </div>
    <div class="inprow">
        <label class="inplabel">Model</label>
        <input id="LaptopModel_Edit" name="LaptopModel_Edit" value="@Model.Laptops.LaptopModel" />
    </div>
    <div class="inprow">
        <label class="inplabel">Problem</label>
        <input id="LaptopProblem_Edit" name="LaptopProblem_Edit" value="@Model.Laptops.LaptopProblem" />
    </div>
    <div class="inprow">
        <label class="inplabel">Work Order</label>
        <select id="LaptopWorkOrder_Edit" class="LaptopWorkorderDropdown" name="LaptopWorkOrder_Edit">
            @foreach (var workOrder in Model.workOrders)
            {
                string current = "";
                if (workOrder.WorkOrderID == Model.Laptops.Workorder.WorkOrderID)
                {
                    current = "selected";
                }

                <option value="@workOrder.WorkOrderID" @current>@workOrder.WorkOrderName</option>
            }

        </select>
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PassionProject/Views/Laptop/Index.cshtml
@model IEnumerable<PassionProject.Models.Laptops>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LaptopManufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LaptopModel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LaptopProblem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Workorder)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LaptopManufacturer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LaptopModel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LaptopProblem)
        </td>
        <td>
            @Html.ActionLink(item.Workorder.WorkOrderName, "Details/" + item.Workorder.WorkOrderID, "WorkOrder")
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.LaptopID }) |
            @Html.ActionLink("Details", "Details", new { id = item.LaptopID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.LaptopID })
        </td>
    </tr>
}

</table>